name: ln_forms
description: Ln form and form fields
version: 1.0.0
repository: https://github.com/orcunoz/ln_forms
publish_to: none

environment:
  sdk: ^3.0.5

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  universal_platform: ^1.0.0+1
  universal_io: ^2.2.2
  quill_html_editor: ^2.2.7
  flutter_html:
  mask_text_input_formatter: ^2.5.0
  url_launcher: ^6.2.1
  image_picker: ^1.0.4
  image_picker_windows: ^0.2.1+1
  logger:
  collection:

  ln_core:
    #path: ../ln_core
    git:
      url: https://github.com/orcunoz/ln_core
      ref: main
  ln_dialogs:
    #path: ../ln_dialogs
    git:
      url: https://github.com/orcunoz/ln_dialogs
      ref: main
  ln_alerts:
    git:
      url: https://github.com/orcunoz/ln_alerts
      ref: main

flutter:
  uses-material-design: true

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
