name: ln_forms
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/orcunoz/ln_forms

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  universal_platform:
  universal_io:
  quill_html_editor: ^2.1.9
  flutter_html:
  mask_text_input_formatter:
  url_launcher:
  image_picker:
  ln_core:
    path: ../ln_core
  ln_dialogs:
    path: ../ln_dialogs

flutter:
  uses-material-design: true

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
